### ISSUE TITLE
Support for terminal URLs

### ISSUE THREAD

**Issue by dharmatech** [buildkite/terminal-to-html#116] opened 2023-08-09 07:29 UTC
This page demonstrates links in terminals:

> https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

Example in bash:

    printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'

What it looks like:

![image](https://github.com/buildkite/terminal-to-html/assets/20816/ecc6705b-bfe2-42ec-9fe6-f8b0b0c5f7b8)

I noticed the README mentions links, but it seems like they're not the same as this `\e[8` kind?

**Comment by DrJosh9000** [comment] 2023-08-16 01:28
Hi @dharmatech, thanks for the feature request!

Sounds like a cool idea! We would love a PR that implements this. Until then I'll stick it on our backlog.

**Comment by dgl** [comment] 2024-03-15 00:12
Dupe of #58 -- while that mentions iTerm2's format, it's actually the "standard" format documented at the link, which iTerm2 supports.

**Closed** 2024-07-08 05:18 UTC
Labels: help wanted
