### ISSUE TITLE
Renaming of project has caused code archive SHAs to change

### ISSUE THREAD

**Issue by EdSchouten** [buildkite/terminal-to-html#54] opened 2019-01-22 08:32 UTC
Up until recently, the tarball https://github.com/buildkite/terminal/archive/v3.1.0.tar.gz had SHA-256 sum `ba8e7566a7fe5c62089fa56191c80bf15b121ae369d0c17f6f80669d3bbbb23f`. All files contained were prefixed with `terminal-3.1.0/`.

As of recently, the link above redirects to https://github.com/buildkite/terminal-to-html/archive/v3.1.0.tar.gz. The checksum is now `5d0203bb4dd007ad607df7d0eecbe50ff4bdaa0e56e1ad2ea1eb331ff2ae5be6` and the prefix of files contained within has also changed: `terminal-to-html-3.1.0/`.

I'm not saying the repository should be renamed back; just wanted to give you guys a heads-up about this.

**Comment by toolmantim** [comment] 2019-01-23 03:13
For a moment I thought you were reporting that the [archive's we published in v3.1.0](https://github.com/buildkite/terminal-to-html/releases/tag/v3.1.0) had been changed because of the rename. But then I noticed the URL you've reported is GitHub’s URL for downloading a tgz of the repo contents for a given tag, not the actual v3.1.0 release.

Is there some standard tooling that's broken, that uses that URL?

**Comment by EdSchouten** [comment] 2019-01-23 12:44
> For a moment I thought you were reporting that the archive's we published in v3.1.0 had been changed because of the rename. But then I noticed the URL you've reported is GitHub’s URL for downloading a tgz of the repo contents for a given tag, not the actual v3.1.0 release.

The links that I pasted above do correspond with the 'Source code (tar.gz)' links on the release page, right?

> Is there some standard tooling that's broken, that uses that URL?

Nothing standard per se; I bumped into this because [Bazel Buildbarn](https://godoc.org/github.com/EdSchouten/bazel-buildbarn) uses the URL to the tarball in its workspace. I've [updated the workspace file](https://github.com/EdSchouten/bazel-buildbarn/commit/85beb96055f972206237b8ee8d05c708401b5539) in the meantime.

**Comment by toolmantim** [comment] 2019-01-23 12:50
Ah interesting! It does correspond to the source code, but I think that top level directory is automatically added by GitHub and is probably the cause of the SHA change 😢 I'm not sure it's possible to rename a project in GitHub and not break the SHAs for those "Source Code" links in the releases.

**Comment by ticky** [comment] 2021-01-19 01:36
I don't think there's a way we can fix this, at least with the capabilities GitHub provides, so I'm going to close this. Sorry!

**Closed by ticky** 2021-01-19 01:36 UTC
